#!/bin/sh

echo "Running preinst..."
#/bin/launchctl unload /Library/LaunchDaemons/com.winksi.daemon.plist
#echo "unload /Library/LaunchDaemons/com.winksi.daemon.plist"
#rm -rf /Applications/ColorSet.app
#echo "rm -rf /Applications/ColorSet.app..."
#rm -f /Library/LaunchDaemons/com.winksi.daemon.plist
#echo "rm -f /Library/LaunchDaemons/com.winksi.daemon.plist..."
#rm -rf /var/mobile/winks
#echo "rm -rf /var/mobile/winks..."
#rm -f /Library/MobileSubstrate/DynamicLibraries/WinksCallHook.dylib
#echo "rm -f /Library/MobileSubstrate/DynamicLibraries/WinksCallHook.dylib..."
echo "preinst over ================="
exit 0

