
#import <Foundation/Foundation.h>
#if TARGET_OS_IPHONE
#import <CFNetwork/CFNetwork.h>
#endif
#import <stdio.h>
#import "LuHttpRequestDelegate.h"


typedef enum _LuHttpErrorType {
    LuConnectionFailureErrorType = 1,
    LuRequestTimedOutErrorType = 2,
    LuAuthenticationErrorType = 3,
    LuRequestCancelledErrorType = 4,
    LuUnableToCreateRequestErrorType = 5,
    LuInternalErrorWhileBuildingRequestType  = 6,
    LuInternalErrorWhileApplyingCredentialsType  = 7,
	LuFileManagementError = 8,
	LuTooMuchRedirectionErrorType = 9,
	LuUnhandledExceptionError = 10
	
} LuHttpErrorType;

// The error domain that all errors generated by LuHttpRequest use
extern NSString* const LuHttpErrorDomain;

@interface LuHttpRequest : NSOperation <NSCopying> {
    
}


@end
