/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package luke.android;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int default_image=0x7f020000;
        public static final int icon=0x7f020001;
        public static final int p1=0x7f020002;
        public static final int p2=0x7f020003;
    }
    public static final class id {
        public static final int avatar=0x7f050006;
        public static final int contacts_list=0x7f050000;
        public static final int icon=0x7f050001;
        public static final int icon_presence=0x7f050004;
        public static final int name=0x7f050002;
        public static final int number=0x7f050003;
        public static final int presence=0x7f050005;
        public static final int rowText1=0x7f050007;
        public static final int rowText2=0x7f050008;
        public static final int row_entry=0x7f05000c;
        public static final int text1=0x7f05000a;
        public static final int text2=0x7f05000b;
        public static final int userText=0x7f050009;
    }
    public static final class layout {
        public static final int callingactivity=0x7f030000;
        public static final int cursor_image_list_item=0x7f030001;
        public static final int friendlist_child=0x7f030002;
        public static final int friendlist_group=0x7f030003;
        public static final int friendlist_tab_layout=0x7f030004;
        public static final int image_list_item=0x7f030005;
        public static final int main=0x7f030006;
        public static final int main_item=0x7f030007;
        public static final int phone_call=0x7f030008;
        public static final int phone_sms=0x7f030009;
        public static final int subactivity=0x7f03000a;
    }
    public static final class string {
        public static final int Expandlist_FriendList=0x7f04000d;
        public static final int PeopleListActivity=0x7f040006;
        public static final int activity_callingactivity=0x7f040002;
        public static final int app_name=0x7f040001;
        public static final int cursor_PeopleListActivity=0x7f040007;
        public static final int empty=0x7f040005;
        public static final int expandableList1=0x7f040009;
        public static final int main=0x7f040000;
        public static final int main_tabs=0x7f040008;
        public static final int phone_call=0x7f04000a;
        public static final int phone_sms=0x7f04000b;
        public static final int search_title=0x7f040004;
        public static final int subactivity=0x7f040003;
        public static final int tabs_expandListTabs=0x7f04000c;
    }
}
