/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package luke.android;

public final class R {
    public static final class array {
        public static final int fileEndingAudio=0x7f050001;
        public static final int fileEndingImage=0x7f050000;
        public static final int fileEndingPackage=0x7f050002;
        public static final int fileEndingWebText=0x7f050003;
        public static final int list_examples=0x7f050004;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int black=0x7f060001;
        public static final int grid_text=0x7f060002;
        public static final int white=0x7f060000;
    }
    public static final class drawable {
        public static final int audio=0x7f020000;
        public static final int default_image=0x7f020001;
        public static final int folder=0x7f020002;
        public static final int goroot=0x7f020003;
        public static final int grouphome_black_bar=0x7f020004;
        public static final int grouphome_focused_application_background=0x7f020005;
        public static final int grouphome_grid_selector=0x7f020006;
        public static final int grouphome_grid_selector_transition=0x7f020007;
        public static final int grouphome_ic_menu_home=0x7f020008;
        public static final int grouphome_ic_menu_refresh=0x7f020009;
        public static final int grouphome_icon=0x7f02000a;
        public static final int grouphome_longpress_application_background=0x7f02000b;
        public static final int grouphome_pressed_application_background=0x7f02000c;
        public static final int grouphome_settings_header=0x7f02000d;
        public static final int grouphome_settings_header_list=0x7f02000e;
        public static final int grouphome_settings_header_raw=0x7f02000f;
        public static final int headerseparatinglist_icon=0x7f020010;
        public static final int icon=0x7f020011;
        public static final int image=0x7f020012;
        public static final int list_filterable_selector_glow=0x7f020013;
        public static final int p1=0x7f020014;
        public static final int p2=0x7f020015;
        public static final int packed=0x7f020016;
        public static final int selector_glow_white=0x7f020017;
        public static final int selector_glow_white_image=0x7f020018;
        public static final int selector_glow_yellow=0x7f020019;
        public static final int selector_glow_yellow_image=0x7f02001a;
        public static final int text=0x7f02001b;
        public static final int todolist_checkmark=0x7f02001c;
        public static final int todolist_ic_text_dot_c=0x7f02001d;
        public static final int todolist_ic_text_dot_c_invert=0x7f02001e;
        public static final int todolist_icon=0x7f02001f;
        public static final int todolist_indicator_check_mark_dark=0x7f020020;
        public static final int todolist_indicator_check_mark_dark_invert=0x7f020021;
        public static final int uponelevel=0x7f020022;
        public static final int webtext=0x7f020023;
    }
    public static final class id {
        public static final int avatar=0x7f090008;
        public static final int contacts_list=0x7f090002;
        public static final int headerSeparatingList_list_complex_caption=0x7f09000c;
        public static final int headerSeparatingList_list_complex_title=0x7f09000b;
        public static final int headerSeparatingList_list_header_title=0x7f09000d;
        public static final int headerSeparatingList_list_item_title=0x7f09000e;
        public static final int icon=0x7f090003;
        public static final int icon_presence=0x7f090006;
        public static final int list_users=0x7f09000f;
        public static final int name=0x7f090004;
        public static final int number=0x7f090005;
        public static final int presence=0x7f090007;
        public static final int result=0x7f090016;
        public static final int rowText1=0x7f090009;
        public static final int rowText2=0x7f09000a;
        public static final int row_entry=0x7f090013;
        public static final int stop=0x7f090015;
        public static final int subactivity_cmd_return=0x7f090001;
        public static final int subactivity_edit_returnvalue=0x7f090000;
        public static final int submit=0x7f090014;
        public static final int text1=0x7f090011;
        public static final int text2=0x7f090012;
        public static final int todolist_crossview=0x7f090017;
        public static final int userText=0x7f090010;
    }
    public static final class layout {
        public static final int app_filebrowser_file_row=0x7f030000;
        public static final int app_filebrowser_filenameinput=0x7f030001;
        public static final int app_filebrowser_main=0x7f030002;
        public static final int callingactivity=0x7f030003;
        public static final int cursor_image_list_item=0x7f030004;
        public static final int friendlist_child=0x7f030005;
        public static final int friendlist_group=0x7f030006;
        public static final int friendlist_tab_layout=0x7f030007;
        public static final int grouphome_act_launch=0x7f030008;
        public static final int grouphome_item_entry=0x7f030009;
        public static final int grouphome_item_header=0x7f03000a;
        public static final int grouphome_item_row=0x7f03000b;
        public static final int headerseparatinglist_list_complex=0x7f03000c;
        public static final int headerseparatinglist_list_header=0x7f03000d;
        public static final int headerseparatinglist_list_item=0x7f03000e;
        public static final int headerseparatinglist_main=0x7f03000f;
        public static final int image_list_item=0x7f030010;
        public static final int list_filterable=0x7f030011;
        public static final int main=0x7f030012;
        public static final int main_item=0x7f030013;
        public static final int phone_call=0x7f030014;
        public static final int phone_sms=0x7f030015;
        public static final int service_mplayer_main=0x7f030016;
        public static final int subactivity=0x7f030017;
        public static final int todolist_dia_newitem=0x7f030018;
        public static final int todolist_main=0x7f030019;
    }
    public static final class raw {
        public static final int gongfu=0x7f040000;
    }
    public static final class string {
        public static final int Expandlist_FriendList=0x7f07000d;
        public static final int PeopleListActivity=0x7f070006;
        public static final int activity_callingactivity=0x7f070002;
        public static final int app_name=0x7f070001;
        public static final int cursor_PeopleListActivity=0x7f070007;
        public static final int empty=0x7f070005;
        public static final int expandableList1=0x7f070009;
        public static final int filebrowser_appname=0x7f070010;
        public static final int filebrowser_current_dir=0x7f070016;
        public static final int filebrowser_dirname_app_name=0x7f070011;
        public static final int filebrowser_dirnameinput_cmd_return=0x7f070013;
        public static final int filebrowser_dirnameinput_hint=0x7f070014;
        public static final int filebrowser_menu_new_folder=0x7f070012;
        public static final int filebrowser_up_one_level=0x7f070015;
        public static final int grouphome_app_name=0x7f070024;
        public static final int headerSeparatingList_app_name=0x7f070022;
        public static final int headerseparatinglist_hello=0x7f070023;
        public static final int main=0x7f070000;
        public static final int main_tabs=0x7f070008;
        public static final int phone_call=0x7f07000a;
        public static final int phone_sms=0x7f07000b;
        public static final int search_title=0x7f070004;
        public static final int service_mplayer_appname=0x7f07000f;
        public static final int service_mplayer_myservice=0x7f07000e;
        public static final int subactivity=0x7f070003;
        public static final int tabs_expandListTabs=0x7f07000c;
        public static final int todolist_appname=0x7f070021;
        public static final int todolist_bind_days=0x7f070019;
        public static final int todolist_bind_hours=0x7f070018;
        public static final int todolist_bind_minutes=0x7f070017;
        public static final int todolist_todo_add=0x7f07001a;
        public static final int todolist_todo_add_hint=0x7f07001c;
        public static final int todolist_todo_add_neg=0x7f07001e;
        public static final int todolist_todo_add_pos=0x7f07001d;
        public static final int todolist_todo_add_title=0x7f07001b;
        public static final int todolist_todo_cross=0x7f07001f;
        public static final int todolist_todo_delete=0x7f070020;
    }
    public static final class style {
        public static final int Theme=0x7f080000;
    }
}
