/*
 * Copyright 1992 by Jutta Degener and Carsten Bormann, Technische
 * Universitaet Berlin.  See the accompanying file "COPYRIGHT" for
 * details.  THERE IS ABSOLUTELY NO WARRANTY FOR THIS SOFTWARE.
 */

/*$Header: /home/cvsroot/project/msnv5/client/iphone/MSN/gsm610/UNPROTO.H,v 1.1 2008/12/15 06:19:24 zenghg Exp $*/

#ifdef	PROTO_H		/* sic */
#undef	PROTO_H

#undef	P
#undef	P0
#undef	P1
#undef	P2
#undef	P3
#undef	P4
#undef	P5
#undef	P6
#undef	P7
#undef	P8

#endif	/* PROTO_H */
