/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bm_comm_CommPort */

#ifndef _Included_bm_comm_CommPort
#define _Included_bm_comm_CommPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bm_comm_CommPort
 * Method:    open
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_bm_comm_CommPort_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     bm_comm_CommPort
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bm_comm_CommPort_close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bm_comm_CommPort
 * Method:    write
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_bm_comm_CommPort_write
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
